------------------------------------------------------------
-- DB 테이블 생성
------------------------------------------------------------

-- 사용자 계정 생성 + 접속권한 설정
-- Alter session set "_ORACLE_SCRIPT" = true;

------------------------------------------------------------
-- 1. 계정 생성
------------------------------------------------------------

-- CREATE USER project IDENTIFIED BY 1234;

------------------------------------------------------------
-- 2. 권한 부여
------------------------------------------------------------

-- GRANT CONNECT, RESOURCE TO project;

------------------------------------------------------------
-- 3. 저장 공간 할당
------------------------------------------------------------

-- ALTER USER project QUOTA UNLIMITED ON USERS;

------------------------------------------------------------
-- 기존 테이블 삭제(오류 무시 가능)
------------------------------------------------------------

DROP TABLE COMMUNITY_TEST CASCADE CONSTRAINTS;
DROP TABLE DATA_TEST CASCADE CONSTRAINTS;
DROP TABLE MEMBER_TEST CASCADE CONSTRAINTS;
DROP TABLE INQUIRY_TEST CASCADE CONSTRAINTS;

------------------------------------------------------------
-- MEMBER 테이블
------------------------------------------------------------

CREATE TABLE MEMBER_TEST (

    -------------------------------------------------
    -- 회원 기본 정보
    -------------------------------------------------

    MEM_ID          VARCHAR2(15) PRIMARY KEY,
    MEM_PASS        VARCHAR2(100) NOT NULL,
    MEM_NAME        VARCHAR2(20) NOT NULL,
    MEM_NICKNAME  VARCHAR2(50) 
);

------------------------------------------------------------
-- DATA_TEST 테이블
------------------------------------------------------------

CREATE TABLE DATA_TEST (

    -------------------------------------------------
    -- 기본키 (자동 증가)
    -------------------------------------------------

    DATA_ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -------------------------------------------------
    -- 회원 FK
    -------------------------------------------------

    MEM_ID          VARCHAR2(15) NOT NULL,
    CHECK_DATE      DATE DEFAULT SYSDATE,

    -------------------------------------------------
    -- 질환 여부
    -------------------------------------------------

    DI1_DG          NUMBER(1),
    DI2_DG          NUMBER(1),
    DE1_DG          NUMBER(1),
    DI3_DG          NUMBER(1),

    -------------------------------------------------
    -- 혈압 / 당뇨 / 지질
    -------------------------------------------------

    HE_HP           NUMBER(1),
    HE_GLU          NUMBER(6,2),
    HE_HBA1C        NUMBER(4,2),
    HE_CHOL         NUMBER(6,2),

    -------------------------------------------------
    -- 비만
    -------------------------------------------------

    HE_BMI          NUMBER(4,2),
    HE_WC           NUMBER(5,2),

    -------------------------------------------------
    -- 생활습관
    -------------------------------------------------

    BS1_1           NUMBER(2),
    BD1_11          NUMBER(2),
    BD2_1           NUMBER(2),
    BE8_1           NUMBER(4),
    PA_AEROBIC      NUMBER(1),

    -------------------------------------------------
    -- 인구사회학 정보
    -------------------------------------------------

    SEX             NUMBER(1),
    AGE             NUMBER(3),
    EDU             NUMBER(1),
    INCM            NUMBER(1),

    -------------------------------------------------
    -- 예측값
    -------------------------------------------------

    PREDICT         NUMBER(5,4),

    -------------------------------------------------
    -- FK
    -------------------------------------------------

    CONSTRAINT FK_MEMBER
        FOREIGN KEY (MEM_ID)
        REFERENCES MEMBER_TEST(MEM_ID)

);

------------------------------------------------------------
-- COMMUNITY_TEST 테이블
------------------------------------------------------------

CREATE TABLE COMMUNITY_TEST (

    -------------------------------------------------
    -- 기본키 
    -------------------------------------------------

    COM_ID         NUMBER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -------------------------------------------------
    -- 회원 FK
    -------------------------------------------------

    MEM_ID          VARCHAR2(15) NOT NULL,

    -------------------------------------------------
    -- 게시글 정보
    -------------------------------------------------

    COM_TITLE       VARCHAR2(200),
    COM_CONTENT     CLOB,

    -------------------------------------------------
    -- 조회수 / 좋아요
    -------------------------------------------------

    COM_VIEW        NUMBER DEFAULT 0,
    COM_LIKE        NUMBER DEFAULT 0,

    -------------------------------------------------
    -- 작성일
    -------------------------------------------------

    COM_CREATED     DATE DEFAULT SYSDATE,

    -------------------------------------------------
    -- FK
    -------------------------------------------------

    CONSTRAINT FK_COMMUNITY_MEMBER
        FOREIGN KEY (MEM_ID)
        REFERENCES MEMBER_TEST(MEM_ID)

);

------------------------------------------------------------
-- COMMENT_TEST 테이블 
-----------------------------------------------------------
CREATE TABLE COMMENT_TEST (
    COM_ID NUMBER NOT NULL,
    MEM_ID VARCHAR2(50) NOT NULL,
    COMMENT_CREATED DATE
    DEFAULT SYSDATE NOT NULL,
    COMMENT_CONTENT VARCHAR2(1000),
    
    CONSTRAINT PK_COMMENT_TEST
    PRIMARY KEY
    (COM_ID, MEM_ID, COMMENT_CREATED),
    
    CONSTRAINT FK_COMMENT_COMMUNITY
    FOREIGN KEY (COM_ID)
    REFERENCES COMMUNITY_TEST(COM_ID),
    
    CONSTRAINT FK_COMMENT_MEMBER
    FOREIGN KEY (MEM_ID)
    REFERENCES MEMBER_TEST(MEM_ID)
);
------------------------------------------------------------
-- INQUIRY_TEST 테이블 
------------------------------------------------------------

CREATE TABLE INQUIRY_TEST (

    INQ_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    MEM_ID VARCHAR2(50) NOT NULL,
    
    INQ_TITLE VARCHAR2(50) NOT NULL,
    
    INQ_CONTENT VARCHAR2(500) NOT NULL,
    INQ_CREATED DATE DEFAULT SYSDATE,

    CONSTRAINT FK_INQUIRY_MEMBER
    FOREIGN KEY (MEM_ID)

    REFERENCES MEMBER_TEST(MEM_ID)

);

------------------------------------------------------------
-- MEMBER_TEST 테스트 데이터
------------------------------------------------------------

INSERT INTO MEMBER_TEST (

    MEM_ID,
    MEM_PHONE,
    MEM_NAME,
    MEM_NICKNAME
)

VALUES (
    'user1',
    '010-3333-3333',
    '홍길동',
    '의적'
);



------------------------------------------------------------
-- DATA_TEST 테스트 데이터
------------------------------------------------------------

INSERT INTO DATA_TEST (

    MEM_ID,
    CHECK_DATE,

    -------------------------------------------------
    -- 질환 여부
    -------------------------------------------------

    DI1_DG,
    DI2_DG,
    DE1_DG,
    DI3_DG,

    -------------------------------------------------
    -- 혈압 / 당뇨 / 지질
    -------------------------------------------------

    HE_HP,
    HE_GLU,
    HE_HBA1C,
    HE_CHOL,

    -------------------------------------------------
    -- 비만
    -------------------------------------------------

    HE_BMI,
    HE_WC,

    -------------------------------------------------
    -- 생활습관
    -------------------------------------------------

    BS1_1,
    BD1_11,
    BD2_1,
    BE8_1,
    PA_AEROBIC,

    -------------------------------------------------
    -- 인구사회학 정보
    -------------------------------------------------

    SEX,
    AGE,
    EDU,
    INCM,

    -------------------------------------------------
    -- 예측값
    -------------------------------------------------

    PREDICT

)

VALUES (

    'user01',
    SYSDATE,

    -------------------------------------------------
    -- 질환 여부
    -------------------------------------------------

    1,
    1,
    1,
    0,

    -------------------------------------------------
    -- 혈압 / 당뇨 / 지질
    -------------------------------------------------

    4,
    126.5,
    6.5,
    220.5,

    -------------------------------------------------
    -- 비만
    -------------------------------------------------

    27.3,
    92.5,

    -------------------------------------------------
    -- 생활습관
    -------------------------------------------------

    2,
    5,
    3,
    9,
    0,

    -------------------------------------------------
    -- 인구사회학 정보
    -------------------------------------------------

    1,
    27,
    4,
    3,

    -------------------------------------------------
    -- 예측값
    -------------------------------------------------

    0.875

);

------------------------------------------------------------
-- COMMUNITY_TEST 테스트 데이터
------------------------------------------------------------

INSERT INTO COMMUNITY_TEST (
    MEM_ID,
    COM_TITLE,
    COM_CONTENT,
    COM_VIEW,
    COM_LIKE,
    COM_CREATED

)

VALUES (

    'user01',
    '건강 관리 팁 공유',
    '매일 30분 이상 걷기 운동을 하고 있습니다.',
    10,
    3,
    SYSDATE

);

------------------------------------------------------------
-- COMMENT_TEST 테스트 데이터
------------------------------------------------------------

INSERT INTO COMMENT_TEST (

    COM_ID,
    MEM_ID,
    COMMENT_CREATED,
    COMMENT_CONTENT

)

VALUES (

    1,
    'test@gmail.com',
    SYSDATE,
    '테스트 댓글'

);

------------------------------------------------------------
-- INQUIRY_TEST 테스트 데이터
------------------------------------------------------------

INSERT INTO INQUIRY_TEST (MEM_ID, INQ_TITLE,INQ_CONTENT) VALUES( 'user1', '게시글 오류', '게시글 수정이 반영되지 않습니다.');

------------------------------------------------------------
-- 조회
------------------------------------------------------------

SELECT * FROM MEMBER_TEST;
SELECT * FROM DATA_TEST;
SELECT * FROM COMMUNITY_TEST;
SELECT * FROM COMMENT_TEST;
SELECT * FROM INQUIRY_TEST;



------------------------------------------------------------
-- 연쇄삭제 처리
------------------------------------------------------------
------------------------------------------------------------
-- 1. DATA_TEST 외래키 수정
------------------------------------------------------------
ALTER TABLE DATA_TEST DROP CONSTRAINT FK_DATA_MEMBER;

ALTER TABLE DATA_TEST 
ADD CONSTRAINT FK_DATA_MEMBER 
FOREIGN KEY (MEM_ID) 
REFERENCES MEMBER_TEST(MEM_ID) ON DELETE CASCADE;

------------------------------------------------------------
-- 2. COMMUNITY_TEST 외래키 수정
------------------------------------------------------------
ALTER TABLE COMMUNITY_TEST DROP CONSTRAINT FK_COMMUNITY_MEMBER;

ALTER TABLE COMMUNITY_TEST 
ADD CONSTRAINT FK_COMMUNITY_MEMBER 
FOREIGN KEY (MEM_ID) 
REFERENCES MEMBER_TEST(MEM_ID) ON DELETE CASCADE;

------------------------------------------------------------
-- 3. COMMENT_TEST 외래키 수정 (2개)
------------------------------------------------------------
ALTER TABLE COMMENT_TEST DROP CONSTRAINT FK_COMMENT_COMMUNITY;

ALTER TABLE COMMENT_TEST 
ADD CONSTRAINT FK_COMMENT_COMMUNITY 
FOREIGN KEY (COM_ID) 
REFERENCES COMMUNITY_TEST(COM_ID) ON DELETE CASCADE;

ALTER TABLE COMMENT_TEST DROP CONSTRAINT FK_COMMENT_MEMBER;

ALTER TABLE COMMENT_TEST 
ADD CONSTRAINT FK_COMMENT_MEMBER 
FOREIGN KEY (MEM_ID) 
REFERENCES MEMBER_TEST(MEM_ID) ON DELETE CASCADE;

------------------------------------------------------------
-- 4. INQUIRY_TEST 외래키 수정
------------------------------------------------------------
ALTER TABLE INQUIRY_TEST DROP CONSTRAINT FK_INQUIRY_MEMBER;

ALTER TABLE INQUIRY_TEST 
ADD CONSTRAINT FK_INQUIRY_MEMBER 
FOREIGN KEY (MEM_ID) 
REFERENCES MEMBER_TEST(MEM_ID) ON DELETE CASCADE;

------------------------------------------------------------
-- 저장
------------------------------------------------------------

COMMIT;